spring:
  config:
    import: optional:file:.env[.properties]
  batch:
    job:
      enabled: false
  application:
    name: backend5
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:backend5}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/batch/core/schema-postgresql.sql
      continue-on-error: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

payment:
  toss:
    secret-key: ${TOSS_PAYMENT_SECRET}

kafka:
  enabled: true
  bootstrap-servers: localhost:9092
  topic:
    async-orders: async-orders
  consumer:
    group-id: async-sample-group
